[tool.black]
line-length = 120
target_version = ['py310']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.mypy]
python_version = 3.10
strict = true
follow_imports = "silent"
